POST http://localhost:8080/persons
content-type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "dni": "12345678",
  "civilStatus": "soltero",
  "dateBirth": "1990-05-10",
  "tutor": "maria perez",
  "phone": "3884011111",
  "gender": "masculino",
  "registrationDate": "2023-01-10",
  "education": {
    "name": "escuela belgrano 2",
    "address": "address",
    "educationLevel": "primario"
  },
  "address": {
    "street": "calle 1 2",
    "district": "barrio centro",
    "locality": "libertador",
    "province": "jujuy"
  },
  "work": {
    "companyName": "empresa ledesma 2",
    "status": "activo",
    "address": "av siempre viva 123",
    "socialWork": true,
    "nameSocialWork": "osde"
  },
  "health": {
    "cudNumber": "cud1001 2",
    "activeCud": true,
    "rehabilitationTreatment": true,
    "diagnostic": "motor",
    "disabilityType": "fisica"
  },
  "benefit": {
    "federalProgram": true,
    "pension": true,
    "auh": true,
    "merchandise": true,
    "freePass": true
  },
  "familyMembers": [
    {
      "firstName": "maria2",
      "lastName": "perez2",
      "dni": "40111111",
      "age": 60,
      "civilStatus": "casado",
      "parentage": "madre",
      "occupation": "ama de casa"
    }
  ]
}


###
GET http://localhost:8080/persons


###
DELETE http://localhost:8080/persons/1


###
GET http://localhost:8080/events


###
POST http://localhost:8080/events
content-type: application/json

{
  "name": "Presentacion test 2",
  "type": "Presentacion",
  "date": "2026-04-02",
  "description": "Evento sobre desarrollo de software",
  "attendees": 12
}